/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/time.h>

#ifndef ACADO_H
#define ACADO_H

#ifndef __MATLAB__
#ifdef __cplusplus
extern "C"
{
#endif
#endif
#include "qpoases/solver.hpp"


/* COMMON DEFINITIONS:              */
/* -------------------------------- */




/* Number of control intervals */
#define ACADO_N   10
/* Number of differential states */
#define ACADO_NX  4
/* Number of differential state derivatives */
#define ACADO_NDX  0
/* Number of algebraic states */
#define ACADO_NXA  0
/* Number of controls */
#define ACADO_NU  1
/* Number of parameters */
#define ACADO_NP  0
/* Number of output functions */
#define NUM_OUTPUTS  0


/* GLOBAL VARIABLES:                */
/* -------------------------------- */
typedef struct ACADOvariables_ {
int resetIntegrator;

/** Matrix of size: 11 x 4 (row major format) */
real_t x[ 44 ];

/** Column vector of size: 10 */
real_t u[ 10 ];

/** Matrix of size: 10 x 4 (row major format) */
real_t xRef[ 40 ];

/** Column vector of size: 10 */
real_t uRef[ 10 ];


} ACADOvariables;


/* GLOBAL WORKSPACE:                */
/* -------------------------------- */
typedef struct ACADOworkspace_ {
/** Column vector of size: 40 */
real_t acado_aux[ 40 ];

/** Row vector of size: 25 */
real_t rk_xxx[ 25 ];

/** Matrix of size: 4 x 24 (row major format) */
real_t rk_kkk[ 96 ];

/** Row vector of size: 25 */
real_t state[ 25 ];

/** Column vector of size: 10 */
real_t g1[ 10 ];

/** Matrix of size: 4 x 10 (row major format) */
real_t H01[ 40 ];

/** Matrix of size: 10 x 10 (row major format) */
real_t H11[ 100 ];

/** Column vector of size: 4 */
real_t deltaX0[ 4 ];

/** Matrix of size: 40 x 4 (row major format) */
real_t C[ 160 ];

/** Matrix of size: 40 x 4 (row major format) */
real_t QC[ 160 ];

/** Matrix of size: 4 x 4 (row major format) */
real_t Gx[ 16 ];

/** Matrix of size: 40 x 10 (row major format) */
real_t E[ 400 ];

/** Matrix of size: 40 x 10 (row major format) */
real_t QE[ 400 ];

/** Column vector of size: 4 */
real_t Gu[ 4 ];

/** Matrix of size: 10 x 4 (row major format) */
real_t Dx[ 40 ];

/** Column vector of size: 40 */
real_t QDx[ 40 ];

/** Column vector of size: 10 */
real_t Du[ 10 ];

/** Column vector of size: 10 */
real_t RDu[ 10 ];


} ACADOworkspace;


/* GLOBAL FORWARD DECLARATIONS:          */
/* ------------------------------------- */
void integrate( real_t* rk_eta );
void acado_rhs_ext( real_t*, real_t* );
void condense1( int index, real_t* yy );
void condense2(  );
void setupQP(  );
void multiplyQC1( real_t* C1, real_t* QC1 );
void multiplyQE1( real_t* E1, real_t* QE1 );
void multiplyQDX1( real_t* Dx1, real_t* QDx1 );
void multiplyRDU1( real_t* Du1, real_t* RDu1 );
void multiplyQC2( real_t* C1, real_t* QC1 );
void multiplyQE2( real_t* E1, real_t* QE1 );
void multiplyQDX2( real_t* Dx1, real_t* QDx1 );
void multiplyC( real_t* Gx, real_t* C1, real_t* C1_new );
void multiplyE( real_t* Gx, real_t* E1, real_t* E1_new );
void multiplyG1( real_t* E, real_t* QDx, real_t* g1 );
void multiplyH01( real_t* C, real_t* QE, real_t* H01 );
void multiplyH11( real_t* E, real_t* QE, real_t* H11 );
real_t getObjectiveValue(  );
void preparationStep(  );
void initialValueEmbedding(  );
int feedbackStep( real_t* x0 );
void shiftControls( real_t* uEnd );
void shiftStates( real_t* xEnd );
real_t getKKT(  );
real_t* getAcadoVariablesX(  );
real_t* getAcadoVariablesU(  );
real_t* getAcadoVariablesXRef(  );
real_t* getAcadoVariablesURef(  );
void printStates(  );
void printControls(  );
real_t getTime(  );
void printHeader(  );
/* ------------------------------------- */


/* EXTERN DECLARATIONS:                  */
/* ------------------------------------- */
extern ACADOworkspace acadoWorkspace;
extern ACADOvariables acadoVariables;
/* ------------------------------------- */
#ifndef __MATLAB__
#ifdef __cplusplus

} /* extern "C" */
#endif
#endif
#endif

/* END OF FILE. */

