/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


real_t* getAcadoVariablesX(  )
{
return acadoVariables.x;
}

real_t* getAcadoVariablesU(  )
{
return acadoVariables.u;
}

real_t* getAcadoVariablesXRef(  )
{
return acadoVariables.xRef;
}

real_t* getAcadoVariablesURef(  )
{
return acadoVariables.uRef;
}

void printStates(  )
{
printf( "acadoVariables.x = \n" );
int run01,run02;
for( run01=0; run01<4; ++run01 ){
  for( run02=0; run02<11; ++run02 )
    printf( "%e \t", acadoVariables.x[run01*11+run02] );
  printf( "\n" );
}
}

void printControls(  )
{
printf( "acadoVariables.u = \n" );
int run01,run02;
for( run01=0; run01<1; ++run01 ){
  for( run02=0; run02<10; ++run02 )
    printf( "%e \t", acadoVariables.u[run01*10+run02] );
  printf( "\n" );
}
}

real_t getTime(  )
{
real_t current_time;
struct timeval theclock;
gettimeofday( &theclock,0 );
current_time = 1.0*theclock.tv_sec + 1.0e-6*theclock.tv_usec;
return current_time;
}

void printHeader(  )
{
    printf("\nACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.\nCopyright (C) 2008-2011 by Boris Houska and Hans Joachim Ferreau, K.U.Leuven.\nDeveloped within the Optimization in Engineering Center (OPTEC) under\nsupervision of Moritz Diehl. All rights reserved.\n\nACADO Toolkit is distributed under the terms of the GNU Lesser\nGeneral Public License 3 in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\nGNU Lesser General Public License for more details.\n\n" );
}

