/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


#include "acado.h"


void preparationStep(  )
{
setupQP(  );
}

void initialValueEmbedding(  )
{
params.lb[0] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[0];
params.lb[1] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[1];
params.lb[2] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[2];
params.lb[3] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[3];
params.lb[4] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[4];
params.lb[5] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[5];
params.lb[6] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[6];
params.lb[7] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[7];
params.lb[8] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[8];
params.lb[9] = (real_t)-1.0000000000000000e+00 - acadoVariables.u[9];
params.ub[0] = (real_t)1.0000000000000000e+00 - acadoVariables.u[0];
params.ub[1] = (real_t)1.0000000000000000e+00 - acadoVariables.u[1];
params.ub[2] = (real_t)1.0000000000000000e+00 - acadoVariables.u[2];
params.ub[3] = (real_t)1.0000000000000000e+00 - acadoVariables.u[3];
params.ub[4] = (real_t)1.0000000000000000e+00 - acadoVariables.u[4];
params.ub[5] = (real_t)1.0000000000000000e+00 - acadoVariables.u[5];
params.ub[6] = (real_t)1.0000000000000000e+00 - acadoVariables.u[6];
params.ub[7] = (real_t)1.0000000000000000e+00 - acadoVariables.u[7];
params.ub[8] = (real_t)1.0000000000000000e+00 - acadoVariables.u[8];
params.ub[9] = (real_t)1.0000000000000000e+00 - acadoVariables.u[9];
params.g[0] = + acadoWorkspace.H01[0]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[10]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[20]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[30]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[0];
params.g[1] = + acadoWorkspace.H01[1]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[11]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[21]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[31]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[1];
params.g[2] = + acadoWorkspace.H01[2]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[12]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[22]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[32]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[2];
params.g[3] = + acadoWorkspace.H01[3]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[13]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[23]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[33]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[3];
params.g[4] = + acadoWorkspace.H01[4]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[14]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[24]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[34]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[4];
params.g[5] = + acadoWorkspace.H01[5]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[15]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[25]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[35]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[5];
params.g[6] = + acadoWorkspace.H01[6]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[16]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[26]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[36]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[6];
params.g[7] = + acadoWorkspace.H01[7]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[17]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[27]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[37]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[7];
params.g[8] = + acadoWorkspace.H01[8]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[18]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[28]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[38]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[8];
params.g[9] = + acadoWorkspace.H01[9]*acadoWorkspace.deltaX0[0] + acadoWorkspace.H01[19]*acadoWorkspace.deltaX0[1] + acadoWorkspace.H01[29]*acadoWorkspace.deltaX0[2] + acadoWorkspace.H01[39]*acadoWorkspace.deltaX0[3] + acadoWorkspace.g1[9];

params.H[0] = acadoWorkspace.H11[0];
params.H[1] = acadoWorkspace.H11[1];
params.H[2] = acadoWorkspace.H11[2];
params.H[3] = acadoWorkspace.H11[3];
params.H[4] = acadoWorkspace.H11[4];
params.H[5] = acadoWorkspace.H11[5];
params.H[6] = acadoWorkspace.H11[6];
params.H[7] = acadoWorkspace.H11[7];
params.H[8] = acadoWorkspace.H11[8];
params.H[9] = acadoWorkspace.H11[9];
params.H[10] = acadoWorkspace.H11[10];
params.H[11] = acadoWorkspace.H11[11];
params.H[12] = acadoWorkspace.H11[12];
params.H[13] = acadoWorkspace.H11[13];
params.H[14] = acadoWorkspace.H11[14];
params.H[15] = acadoWorkspace.H11[15];
params.H[16] = acadoWorkspace.H11[16];
params.H[17] = acadoWorkspace.H11[17];
params.H[18] = acadoWorkspace.H11[18];
params.H[19] = acadoWorkspace.H11[19];
params.H[20] = acadoWorkspace.H11[20];
params.H[21] = acadoWorkspace.H11[21];
params.H[22] = acadoWorkspace.H11[22];
params.H[23] = acadoWorkspace.H11[23];
params.H[24] = acadoWorkspace.H11[24];
params.H[25] = acadoWorkspace.H11[25];
params.H[26] = acadoWorkspace.H11[26];
params.H[27] = acadoWorkspace.H11[27];
params.H[28] = acadoWorkspace.H11[28];
params.H[29] = acadoWorkspace.H11[29];
params.H[30] = acadoWorkspace.H11[30];
params.H[31] = acadoWorkspace.H11[31];
params.H[32] = acadoWorkspace.H11[32];
params.H[33] = acadoWorkspace.H11[33];
params.H[34] = acadoWorkspace.H11[34];
params.H[35] = acadoWorkspace.H11[35];
params.H[36] = acadoWorkspace.H11[36];
params.H[37] = acadoWorkspace.H11[37];
params.H[38] = acadoWorkspace.H11[38];
params.H[39] = acadoWorkspace.H11[39];
params.H[40] = acadoWorkspace.H11[40];
params.H[41] = acadoWorkspace.H11[41];
params.H[42] = acadoWorkspace.H11[42];
params.H[43] = acadoWorkspace.H11[43];
params.H[44] = acadoWorkspace.H11[44];
params.H[45] = acadoWorkspace.H11[45];
params.H[46] = acadoWorkspace.H11[46];
params.H[47] = acadoWorkspace.H11[47];
params.H[48] = acadoWorkspace.H11[48];
params.H[49] = acadoWorkspace.H11[49];
params.H[50] = acadoWorkspace.H11[50];
params.H[51] = acadoWorkspace.H11[51];
params.H[52] = acadoWorkspace.H11[52];
params.H[53] = acadoWorkspace.H11[53];
params.H[54] = acadoWorkspace.H11[54];
params.H[55] = acadoWorkspace.H11[55];
params.H[56] = acadoWorkspace.H11[56];
params.H[57] = acadoWorkspace.H11[57];
params.H[58] = acadoWorkspace.H11[58];
params.H[59] = acadoWorkspace.H11[59];
params.H[60] = acadoWorkspace.H11[60];
params.H[61] = acadoWorkspace.H11[61];
params.H[62] = acadoWorkspace.H11[62];
params.H[63] = acadoWorkspace.H11[63];
params.H[64] = acadoWorkspace.H11[64];
params.H[65] = acadoWorkspace.H11[65];
params.H[66] = acadoWorkspace.H11[66];
params.H[67] = acadoWorkspace.H11[67];
params.H[68] = acadoWorkspace.H11[68];
params.H[69] = acadoWorkspace.H11[69];
params.H[70] = acadoWorkspace.H11[70];
params.H[71] = acadoWorkspace.H11[71];
params.H[72] = acadoWorkspace.H11[72];
params.H[73] = acadoWorkspace.H11[73];
params.H[74] = acadoWorkspace.H11[74];
params.H[75] = acadoWorkspace.H11[75];
params.H[76] = acadoWorkspace.H11[76];
params.H[77] = acadoWorkspace.H11[77];
params.H[78] = acadoWorkspace.H11[78];
params.H[79] = acadoWorkspace.H11[79];
params.H[80] = acadoWorkspace.H11[80];
params.H[81] = acadoWorkspace.H11[81];
params.H[82] = acadoWorkspace.H11[82];
params.H[83] = acadoWorkspace.H11[83];
params.H[84] = acadoWorkspace.H11[84];
params.H[85] = acadoWorkspace.H11[85];
params.H[86] = acadoWorkspace.H11[86];
params.H[87] = acadoWorkspace.H11[87];
params.H[88] = acadoWorkspace.H11[88];
params.H[89] = acadoWorkspace.H11[89];
params.H[90] = acadoWorkspace.H11[90];
params.H[91] = acadoWorkspace.H11[91];
params.H[92] = acadoWorkspace.H11[92];
params.H[93] = acadoWorkspace.H11[93];
params.H[94] = acadoWorkspace.H11[94];
params.H[95] = acadoWorkspace.H11[95];
params.H[96] = acadoWorkspace.H11[96];
params.H[97] = acadoWorkspace.H11[97];
params.H[98] = acadoWorkspace.H11[98];
params.H[99] = acadoWorkspace.H11[99];
}

int feedbackStep( real_t* x0 )
{
int retVal;
acadoWorkspace.deltaX0[0] = x0[0] - acadoVariables.x[0];
acadoWorkspace.deltaX0[1] = x0[1] - acadoVariables.x[1];
acadoWorkspace.deltaX0[2] = x0[2] - acadoVariables.x[2];
acadoWorkspace.deltaX0[3] = x0[3] - acadoVariables.x[3];

initialValueEmbedding(  );

retVal = (int) solve();

acadoVariables.u[0] += vars.x[0];
acadoVariables.u[1] += vars.x[1];
acadoVariables.u[2] += vars.x[2];
acadoVariables.u[3] += vars.x[3];
acadoVariables.u[4] += vars.x[4];
acadoVariables.u[5] += vars.x[5];
acadoVariables.u[6] += vars.x[6];
acadoVariables.u[7] += vars.x[7];
acadoVariables.u[8] += vars.x[8];
acadoVariables.u[9] += vars.x[9];
acadoVariables.x[0] += acadoWorkspace.deltaX0[0];
acadoVariables.x[1] += acadoWorkspace.deltaX0[1];
acadoVariables.x[2] += acadoWorkspace.deltaX0[2];
acadoVariables.x[3] += acadoWorkspace.deltaX0[3];
return retVal;
}

void shiftControls( real_t* uEnd )
{
acadoVariables.u[0] = acadoVariables.u[1];
acadoVariables.u[1] = acadoVariables.u[2];
acadoVariables.u[2] = acadoVariables.u[3];
acadoVariables.u[3] = acadoVariables.u[4];
acadoVariables.u[4] = acadoVariables.u[5];
acadoVariables.u[5] = acadoVariables.u[6];
acadoVariables.u[6] = acadoVariables.u[7];
acadoVariables.u[7] = acadoVariables.u[8];
acadoVariables.u[8] = acadoVariables.u[9];

if (uEnd != NULL)
{acadoVariables.u[9] = uEnd[0];
}}

void shiftStates( real_t* xEnd )
{
acadoVariables.x[0] = acadoVariables.x[4];
acadoVariables.x[1] = acadoVariables.x[5];
acadoVariables.x[2] = acadoVariables.x[6];
acadoVariables.x[3] = acadoVariables.x[7];
acadoVariables.x[4] = acadoVariables.x[8];
acadoVariables.x[5] = acadoVariables.x[9];
acadoVariables.x[6] = acadoVariables.x[10];
acadoVariables.x[7] = acadoVariables.x[11];
acadoVariables.x[8] = acadoVariables.x[12];
acadoVariables.x[9] = acadoVariables.x[13];
acadoVariables.x[10] = acadoVariables.x[14];
acadoVariables.x[11] = acadoVariables.x[15];
acadoVariables.x[12] = acadoVariables.x[16];
acadoVariables.x[13] = acadoVariables.x[17];
acadoVariables.x[14] = acadoVariables.x[18];
acadoVariables.x[15] = acadoVariables.x[19];
acadoVariables.x[16] = acadoVariables.x[20];
acadoVariables.x[17] = acadoVariables.x[21];
acadoVariables.x[18] = acadoVariables.x[22];
acadoVariables.x[19] = acadoVariables.x[23];
acadoVariables.x[20] = acadoVariables.x[24];
acadoVariables.x[21] = acadoVariables.x[25];
acadoVariables.x[22] = acadoVariables.x[26];
acadoVariables.x[23] = acadoVariables.x[27];
acadoVariables.x[24] = acadoVariables.x[28];
acadoVariables.x[25] = acadoVariables.x[29];
acadoVariables.x[26] = acadoVariables.x[30];
acadoVariables.x[27] = acadoVariables.x[31];
acadoVariables.x[28] = acadoVariables.x[32];
acadoVariables.x[29] = acadoVariables.x[33];
acadoVariables.x[30] = acadoVariables.x[34];
acadoVariables.x[31] = acadoVariables.x[35];
acadoVariables.x[32] = acadoVariables.x[36];
acadoVariables.x[33] = acadoVariables.x[37];
acadoVariables.x[34] = acadoVariables.x[38];
acadoVariables.x[35] = acadoVariables.x[39];
acadoVariables.x[36] = acadoVariables.x[40];
acadoVariables.x[37] = acadoVariables.x[41];
acadoVariables.x[38] = acadoVariables.x[42];
acadoVariables.x[39] = acadoVariables.x[43];

if (xEnd != NULL)
{acadoVariables.x[40] = xEnd[0];
acadoVariables.x[41] = xEnd[1];
acadoVariables.x[42] = xEnd[2];
acadoVariables.x[43] = xEnd[3];
}}

real_t getKKT(  )
{
real_t tmp;
tmp = + acadoWorkspace.g1[0]*vars.x[0] + acadoWorkspace.g1[1]*vars.x[1] + acadoWorkspace.g1[2]*vars.x[2] + acadoWorkspace.g1[3]*vars.x[3] + acadoWorkspace.g1[4]*vars.x[4] + acadoWorkspace.g1[5]*vars.x[5] + acadoWorkspace.g1[6]*vars.x[6] + acadoWorkspace.g1[7]*vars.x[7] + acadoWorkspace.g1[8]*vars.x[8] + acadoWorkspace.g1[9]*vars.x[9];
tmp = fabs( tmp );
return tmp;
}

