/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


#include "acado.h"


void acado_rhs_ext( real_t *acado_x, real_t *acado_f ){
real_t *acado_xd = acado_x;
real_t *acado_u  = acado_x + 24;

/* COMPUTE INTERMEDIATE STATES: */
/* ---------------------------- */
acadoWorkspace.acado_aux[16] = acado_xd[8];
acadoWorkspace.acado_aux[17] = acado_xd[9];
acadoWorkspace.acado_aux[18] = acado_xd[10];
acadoWorkspace.acado_aux[19] = acado_xd[11];
acadoWorkspace.acado_aux[4] = (real_t)(0.);
acadoWorkspace.acado_aux[5] = (real_t)(0.);
acadoWorkspace.acado_aux[6] = (real_t)(0.);
acadoWorkspace.acado_aux[7] = (real_t)(0.);
acadoWorkspace.acado_aux[20] = acado_xd[16];
acadoWorkspace.acado_aux[21] = acado_xd[17];
acadoWorkspace.acado_aux[22] = acado_xd[18];
acadoWorkspace.acado_aux[23] = acado_xd[19];
acadoWorkspace.acado_aux[24] = ((((real_t)(-9.81)*(cos(acado_xd[2])))-(acado_u[0]*((real_t)(-1.)*(sin(acado_xd[2])))))*acado_xd[12]);
acadoWorkspace.acado_aux[25] = (acadoWorkspace.acado_aux[24]+(((real_t)(0.)-(real_t)(0.2))*acado_xd[16]));
acadoWorkspace.acado_aux[26] = ((((real_t)(-9.81)*(cos(acado_xd[2])))-(acado_u[0]*((real_t)(-1.)*(sin(acado_xd[2])))))*acado_xd[13]);
acadoWorkspace.acado_aux[27] = (acadoWorkspace.acado_aux[26]+(((real_t)(0.)-(real_t)(0.2))*acado_xd[17]));
acadoWorkspace.acado_aux[28] = ((((real_t)(-9.81)*(cos(acado_xd[2])))-(acado_u[0]*((real_t)(-1.)*(sin(acado_xd[2])))))*acado_xd[14]);
acadoWorkspace.acado_aux[29] = (acadoWorkspace.acado_aux[28]+(((real_t)(0.)-(real_t)(0.2))*acado_xd[18]));
acadoWorkspace.acado_aux[30] = ((((real_t)(-9.81)*(cos(acado_xd[2])))-(acado_u[0]*((real_t)(-1.)*(sin(acado_xd[2])))))*acado_xd[15]);
acadoWorkspace.acado_aux[31] = (acadoWorkspace.acado_aux[30]+(((real_t)(0.)-(real_t)(0.2))*acado_xd[19]));
acadoWorkspace.acado_aux[36] = acado_xd[21];
acadoWorkspace.acado_aux[37] = acado_xd[23];
acadoWorkspace.acado_aux[38] = ((((real_t)(-9.81)*(cos(acado_xd[2])))-(acado_u[0]*((real_t)(-1.)*(sin(acado_xd[2])))))*acado_xd[22]);
acadoWorkspace.acado_aux[39] = (acadoWorkspace.acado_aux[38]+(((real_t)(0.)-(real_t)(0.2))*acado_xd[23]));

/* COMPUTE OUTPUT: */
/* --------------- */
acado_f[0] = acado_xd[1];
acado_f[1] = acado_u[0];
acado_f[2] = acado_xd[3];
acado_f[3] = ((((real_t)(-9.81)*(sin(acado_xd[2])))-(acado_u[0]*(cos(acado_xd[2]))))-((real_t)(0.2)*acado_xd[3]));
acado_f[4] = acadoWorkspace.acado_aux[16];
acado_f[5] = acadoWorkspace.acado_aux[17];
acado_f[6] = acadoWorkspace.acado_aux[18];
acado_f[7] = acadoWorkspace.acado_aux[19];
acado_f[8] = acadoWorkspace.acado_aux[4];
acado_f[9] = acadoWorkspace.acado_aux[5];
acado_f[10] = acadoWorkspace.acado_aux[6];
acado_f[11] = acadoWorkspace.acado_aux[7];
acado_f[12] = acadoWorkspace.acado_aux[20];
acado_f[13] = acadoWorkspace.acado_aux[21];
acado_f[14] = acadoWorkspace.acado_aux[22];
acado_f[15] = acadoWorkspace.acado_aux[23];
acado_f[16] = acadoWorkspace.acado_aux[25];
acado_f[17] = acadoWorkspace.acado_aux[27];
acado_f[18] = acadoWorkspace.acado_aux[29];
acado_f[19] = acadoWorkspace.acado_aux[31];
acado_f[20] = acadoWorkspace.acado_aux[36];
acado_f[21] = (real_t)(1.);
acado_f[22] = acadoWorkspace.acado_aux[37];
acado_f[23] = (acadoWorkspace.acado_aux[39]+((real_t)(0.)-(cos(acado_xd[2]))));
}

void integrate( real_t* rk_eta )
{
int run1;
rk_eta[4] = 1.0000000000000000e+00;
rk_eta[5] = 0.0000000000000000e+00;
rk_eta[6] = 0.0000000000000000e+00;
rk_eta[7] = 0.0000000000000000e+00;
rk_eta[8] = 0.0000000000000000e+00;
rk_eta[9] = 1.0000000000000000e+00;
rk_eta[10] = 0.0000000000000000e+00;
rk_eta[11] = 0.0000000000000000e+00;
rk_eta[12] = 0.0000000000000000e+00;
rk_eta[13] = 0.0000000000000000e+00;
rk_eta[14] = 1.0000000000000000e+00;
rk_eta[15] = 0.0000000000000000e+00;
rk_eta[16] = 0.0000000000000000e+00;
rk_eta[17] = 0.0000000000000000e+00;
rk_eta[18] = 0.0000000000000000e+00;
rk_eta[19] = 1.0000000000000000e+00;
rk_eta[20] = 0.0000000000000000e+00;
rk_eta[21] = 0.0000000000000000e+00;
rk_eta[22] = 0.0000000000000000e+00;
rk_eta[23] = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[24] = rk_eta[24];

for (run1 = 0; run1 < 3; ++run1)
{
acadoWorkspace.rk_xxx[0] = + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + rk_eta[5];
acadoWorkspace.rk_xxx[6] = + rk_eta[6];
acadoWorkspace.rk_xxx[7] = + rk_eta[7];
acadoWorkspace.rk_xxx[8] = + rk_eta[8];
acadoWorkspace.rk_xxx[9] = + rk_eta[9];
acadoWorkspace.rk_xxx[10] = + rk_eta[10];
acadoWorkspace.rk_xxx[11] = + rk_eta[11];
acadoWorkspace.rk_xxx[12] = + rk_eta[12];
acadoWorkspace.rk_xxx[13] = + rk_eta[13];
acadoWorkspace.rk_xxx[14] = + rk_eta[14];
acadoWorkspace.rk_xxx[15] = + rk_eta[15];
acadoWorkspace.rk_xxx[16] = + rk_eta[16];
acadoWorkspace.rk_xxx[17] = + rk_eta[17];
acadoWorkspace.rk_xxx[18] = + rk_eta[18];
acadoWorkspace.rk_xxx[19] = + rk_eta[19];
acadoWorkspace.rk_xxx[20] = + rk_eta[20];
acadoWorkspace.rk_xxx[21] = + rk_eta[21];
acadoWorkspace.rk_xxx[22] = + rk_eta[22];
acadoWorkspace.rk_xxx[23] = + rk_eta[23];
acado_rhs_ext( acadoWorkspace.rk_xxx, acadoWorkspace.rk_kkk );
acadoWorkspace.rk_xxx[0] = + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + rk_eta[5];
acadoWorkspace.rk_xxx[6] = + rk_eta[6];
acadoWorkspace.rk_xxx[7] = + rk_eta[7];
acadoWorkspace.rk_xxx[8] = + rk_eta[8];
acadoWorkspace.rk_xxx[9] = + rk_eta[9];
acadoWorkspace.rk_xxx[10] = + rk_eta[10];
acadoWorkspace.rk_xxx[11] = + rk_eta[11];
acadoWorkspace.rk_xxx[12] = + rk_eta[12];
acadoWorkspace.rk_xxx[13] = + rk_eta[13];
acadoWorkspace.rk_xxx[14] = + rk_eta[14];
acadoWorkspace.rk_xxx[15] = + rk_eta[15];
acadoWorkspace.rk_xxx[16] = + rk_eta[16];
acadoWorkspace.rk_xxx[17] = + rk_eta[17];
acadoWorkspace.rk_xxx[18] = + rk_eta[18];
acadoWorkspace.rk_xxx[19] = + rk_eta[19];
acadoWorkspace.rk_xxx[20] = + rk_eta[20];
acadoWorkspace.rk_xxx[21] = + rk_eta[21];
acadoWorkspace.rk_xxx[22] = + rk_eta[22];
acadoWorkspace.rk_xxx[23] = + rk_eta[23];
acado_rhs_ext( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 24 ]) );
acadoWorkspace.rk_xxx[0] = + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + rk_eta[5];
acadoWorkspace.rk_xxx[6] = + rk_eta[6];
acadoWorkspace.rk_xxx[7] = + rk_eta[7];
acadoWorkspace.rk_xxx[8] = + rk_eta[8];
acadoWorkspace.rk_xxx[9] = + rk_eta[9];
acadoWorkspace.rk_xxx[10] = + rk_eta[10];
acadoWorkspace.rk_xxx[11] = + rk_eta[11];
acadoWorkspace.rk_xxx[12] = + rk_eta[12];
acadoWorkspace.rk_xxx[13] = + rk_eta[13];
acadoWorkspace.rk_xxx[14] = + rk_eta[14];
acadoWorkspace.rk_xxx[15] = + rk_eta[15];
acadoWorkspace.rk_xxx[16] = + rk_eta[16];
acadoWorkspace.rk_xxx[17] = + rk_eta[17];
acadoWorkspace.rk_xxx[18] = + rk_eta[18];
acadoWorkspace.rk_xxx[19] = + rk_eta[19];
acadoWorkspace.rk_xxx[20] = + rk_eta[20];
acadoWorkspace.rk_xxx[21] = + rk_eta[21];
acadoWorkspace.rk_xxx[22] = + rk_eta[22];
acadoWorkspace.rk_xxx[23] = + rk_eta[23];
acado_rhs_ext( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 48 ]) );
acadoWorkspace.rk_xxx[0] = + rk_eta[0];
acadoWorkspace.rk_xxx[1] = + rk_eta[1];
acadoWorkspace.rk_xxx[2] = + rk_eta[2];
acadoWorkspace.rk_xxx[3] = + rk_eta[3];
acadoWorkspace.rk_xxx[4] = + rk_eta[4];
acadoWorkspace.rk_xxx[5] = + rk_eta[5];
acadoWorkspace.rk_xxx[6] = + rk_eta[6];
acadoWorkspace.rk_xxx[7] = + rk_eta[7];
acadoWorkspace.rk_xxx[8] = + rk_eta[8];
acadoWorkspace.rk_xxx[9] = + rk_eta[9];
acadoWorkspace.rk_xxx[10] = + rk_eta[10];
acadoWorkspace.rk_xxx[11] = + rk_eta[11];
acadoWorkspace.rk_xxx[12] = + rk_eta[12];
acadoWorkspace.rk_xxx[13] = + rk_eta[13];
acadoWorkspace.rk_xxx[14] = + rk_eta[14];
acadoWorkspace.rk_xxx[15] = + rk_eta[15];
acadoWorkspace.rk_xxx[16] = + rk_eta[16];
acadoWorkspace.rk_xxx[17] = + rk_eta[17];
acadoWorkspace.rk_xxx[18] = + rk_eta[18];
acadoWorkspace.rk_xxx[19] = + rk_eta[19];
acadoWorkspace.rk_xxx[20] = + rk_eta[20];
acadoWorkspace.rk_xxx[21] = + rk_eta[21];
acadoWorkspace.rk_xxx[22] = + rk_eta[22];
acadoWorkspace.rk_xxx[23] = + rk_eta[23];
acado_rhs_ext( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_kkk[ 72 ]) );
rk_eta[0] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[0] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[24] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[48] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[72];
rk_eta[1] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[1] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[25] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[49] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[73];
rk_eta[2] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[2] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[26] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[50] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[74];
rk_eta[3] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[3] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[27] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[51] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[75];
rk_eta[4] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[4] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[28] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[52] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[76];
rk_eta[5] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[5] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[29] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[53] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[77];
rk_eta[6] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[6] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[30] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[54] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[78];
rk_eta[7] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[7] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[31] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[55] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[79];
rk_eta[8] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[8] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[32] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[56] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[80];
rk_eta[9] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[9] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[33] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[57] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[81];
rk_eta[10] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[10] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[34] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[58] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[82];
rk_eta[11] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[11] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[35] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[59] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[83];
rk_eta[12] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[12] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[36] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[60] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[84];
rk_eta[13] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[13] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[37] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[61] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[85];
rk_eta[14] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[14] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[38] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[62] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[86];
rk_eta[15] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[15] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[39] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[63] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[87];
rk_eta[16] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[16] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[40] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[64] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[88];
rk_eta[17] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[17] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[41] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[65] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[89];
rk_eta[18] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[18] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[42] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[66] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[90];
rk_eta[19] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[19] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[43] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[67] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[91];
rk_eta[20] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[20] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[44] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[68] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[92];
rk_eta[21] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[21] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[45] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[69] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[93];
rk_eta[22] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[22] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[46] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[70] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[94];
rk_eta[23] += + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[23] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[47] + (real_t)3.3333333333333326e-02*acadoWorkspace.rk_kkk[71] + (real_t)1.6666666666666663e-02*acadoWorkspace.rk_kkk[95];
}
}

