/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      10
#define QPOASES_NCMAX      1
#define QPOASES_NWSRMAX    30
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
/** Matrix of size: 10 x 10 (row major format) */
real_t H[ 100 ];

/** Column vector of size: 10 */
real_t g[ 10 ];

/** Column vector of size: 10 */
real_t lb[ 10 ];

/** Column vector of size: 10 */
real_t ub[ 10 ];

} Params;

typedef struct Vars_t {
/** Column vector of size: 10 */
real_t x[ 10 ];

/** Column vector of size: 10 */
real_t y[ 10 ];

} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
